#!/usr/bin/python2.3

from wxPython.wx import *
import weatherfeed, sys

ID_ABOUT    = 101
ID_EXIT     = 102
ID_LOCATION = 103

about = """\
Copyright Dan Cardamore and
Michael Soulier, 2004"""

class CtwFrame(wxFrame):
    def __init__(self, parent, ID, title):
        wxFrame.__init__(self, parent, ID, title,
                         wxDefaultPosition, wxSize(500, 500))
        self.CreateStatusBar()
        self.SetStatusText("This is the statusbar")

        menuFile = wxMenu()
        menuFile.Append(ID_ABOUT, "&About",
                "More information about this program")
        menuFile.AppendSeparator()
        menuFile.Append(ID_EXIT, "E&xit", "Terminate the program")

        menuSettings = wxMenu()
        menuSettings.Append(ID_LOCATION, "&Location",
                "Set your desired location")

        menuBar = wxMenuBar()
        menuBar.Append(menuFile, "&File");
        menuBar.Append(menuSettings, "&Settings");

        self.SetMenuBar(menuBar)

        EVT_MENU(self, ID_ABOUT, self.OnAbout)
        EVT_MENU(self, ID_EXIT, self.OnExit)

    def OnAbout(self, event):
        global dialog
        dialog = wxMessageDialog(self, about, "Curse the Weather", wxOK)
        dialog.ShowModal()
        dialog.Destroy()

    def OnExit(self, event):
        self.Close(true)

class CtwGui(wxApp):
    def OnInit(self):
        frame = CtwFrame(NULL, -1, "Curse the Weather")
        frame.Show(true)
        self.SetTopWindow(frame)
        return true

def main():
    gui = CtwGui(0)
    gui.MainLoop()

if __name__ == '__main__':
    main()
