#!/usr/bin/python2.2

from wxPython.wx import *
import weatherfeed, sys

ID_ABOUT = 101
ID_EXIT  = 102

class CtwFrame(wxFrame):
    def __init__(self, parent, ID, title):
        wxFrame.__init__(self, parent, ID, title,
                         wxDefaultPosition, wxSize(200, 150))
        self.CreateStatusBar()
        self.SetStatusText("This is the statusbar")

        menu = wxMenu()
        menu.Append(ID_ABOUT, "&About",
                    "More information about this program")
        menu.AppendSeparator()
        menu.Append(ID_EXIT, "E&xit", "Terminate the program")

        menuBar = wxMenuBar()
        menuBar.Append(menu, "&File");

        self.SetMenuBar(menuBar)

class CtwGui(wxApp):
    def OnInit(self):
        frame = CtwFrame(NULL, -1, "Curse the Weather")
        frame.Show(true)
        self.SetTopWindow(frame)
        return true

def main():
    gui = CtwGui(0)
    gui.MainLoop()

if __name__ == '__main__':
    main()
